name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches:
      - 'main'
      - 'build_*'
  # run it during pull request
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest'] # later add others like 'ubuntu-latest', 'macos-latest'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile --distpath splinterlands-battle-stats src/main.py
    - run: cp "config.properties" "splinterlands-battle-stats/"

    - if: matrix.os == 'ubuntu-latest'
      run: |
        mv "splinterlands-battle-stats/main" "splinterlands-battle-stats/main.sh"
        tar -cvf splinterlands-battle-stats.tar splinterlands-battle-stats

    - if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: splinterlands-battle-stats-${{ matrix.os }}
        path: splinterlands-battle-stats.tar

    - if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: splinterlands-battle-stats-${{ matrix.os }}
        path: ./splinterlands-battle-stats/*


  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push  splinterlands-battle-stats docker image
        run: |
               docker build . --tag ghcr.io/gamerbeaker007/splinterlands-battle-stats:latest
               docker push ghcr.io/gamerbeaker007/splinterlands-battle-stats:latest
